#pragma once

#include <cstdint>

enum EAppState : int
{
	APPSTATE_INVALID = 0x0,
	APPSTATE_UNINSTALLED = 0x1,
	APPSTATE_UPDATE_REQUIRED = 0x2,
	APPSTATE_FULLY_INSTALLED = 0x4,
	APPSTATE_UPDATE_QUEUED = 0x8,
	APPSTATE_UPDATE_OPTIONAL = 0x10,
	APPSTATE_FILES_MISSING = 0x20,
	APPSTATE_SHARED_ONLY = 0x40,
	APPSTATE_FILES_CORRUPT = 0x80,
	APPSTATE_UPDATE_RUNNING = 0x100,
	APPSTATE_UPDATE_PAUSED = 0x200,
	APPSTATE_UPDATE_STARTED = 0x400,
	APPSTATE_UNINSTALLING = 0x800,
	APPSTATE_BACKUP_RUNNING = 0x1000,
	APPSTATE_APP_RUNNING = 0x2000,
	APPSTATE_COMPONENT_IN_USE = 0x4000,
	APPSTATE_MOVING_FOLDER = 0x8000,
	APPSTATE_TERMINATING = 0x10000,
	APPSTATE_PREFETCHING_INFO = 0x20000,
	APPSTATE_PEER_SERVER = 0x40000,
	APPSTATE_UPDATED_DISABLED_BY_APP = 0x80000,
};

class IClientAppManager
{
public:
	bool installApp(uint32_t appId, uint32_t librarIndex);
	EAppState getAppInstallState(uint32_t appId);
};

extern IClientAppManager* g_pClientAppManager;
